### ISSUE TITLE
liveness check does not detect when kubed is not responding to API requests anymore

### ISSUE THREAD

**Issue by sebastiansirch** [appscode/kubed#343]
We observed exactly the issue described here

https://github.com/appscode/kubed/issues/316#issuecomment-475016157

```
kubectl create ns test
kubectl delete ns test
# not responding anymore
# namespace is stuck in status Terminating with finalizers = kubernetes
```

We did find out that kubed was the root cause because the kubed pod did not respond anymore to k8s api requests (in our case due to some memory error, see below). However, the liveness check did not detect this issue. A more sensible liveness check and therefore an automatic recreation of the kubed pod could already help as a workaround.

```
Apr 10 02:42:32 kube-system kubed-kubed-86f55985f4-6jz2j:  I0410 00:42:32.513494       1 logs.go:19] cron: panic running job: runtime error: invalid memory address or nil pointer dereference
Apr 10 02:42:32 kube-system kubed-kubed-86f55985f4-6jz2j:  created by github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).run
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:199 +0x6f4
Apr 10 02:42:32 kube-system kubed-kubed-86f55985f4-6jz2j:  github.com/appscode/kubed/pkg/recyclebin.(*RecycleBin).Cleanup(0xc0002ed2c0, 0xc04c443790, 0x42b1d2)
	/go/src/github.com/appscode/kubed/pkg/recyclebin/recycle_bin.go:115 +0x9c
Apr 10 02:42:32 kube-system kubed-kubed-86f55985f4-6jz2j:  github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).runWithRecovery.func1(0xc00061f9a0)
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:161 +0xbc
Apr 11 02:07:33 kube-system kubed-kubed-86f55985f4-6jz2j:  github.com/appscode/kubed/pkg/recyclebin.(*RecycleBin).Cleanup(0xc0002ed2c0, 0xc102fcc790, 0x42b1d2)
	/go/src/github.com/appscode/kubed/pkg/recyclebin/recycle_bin.go:115 +0x9c
Apr 11 02:07:33 kube-system kubed-kubed-86f55985f4-6jz2j:  github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).runWithRecovery(0xc00061f9a0, 0x48950c0, 0xc0010036c0)
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:165 +0x57
Apr 11 02:07:33 kube-system kubed-kubed-86f55985f4-6jz2j:  github.com/appscode/kubed/vendor/github.com/robfig/cron.FuncJob.Run(0xc0010036c0)
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:92 +0x25
Apr 11 02:07:33 kube-system kubed-kubed-86f55985f4-6jz2j:  github.com/appscode/kubed/pkg/operator.(*Operator).RunTrashCanCleaner.func1()
	/go/src/github.com/appscode/kubed/pkg/operator/operator.go:489 +0x2e
Apr 11 02:07:33 kube-system kubed-kubed-86f55985f4-6jz2j:  created by github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).run
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:199 +0x6f4
Apr 11 02:07:33 kube-system kubed-kubed-86f55985f4-6jz2j:  github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).runWithRecovery.func1(0xc00061f9a0)
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:161 +0xbc
Apr 11 02:07:33 kube-system kubed-kubed-86f55985f4-6jz2j:  I0411 00:07:33.518744       1 logs.go:19] cron: panic running job: runtime error: invalid memory address or nil pointer dereference
Apr 11 02:13:44 kube-system kubed-kubed-86f55985f4-6jz2j:  github.com/appscode/kubed/vendor/golang.org/x/net/http2.(*serverConn).runHandler(0xc000bc6000, 0xc018862310, 0xc0b56ecb00, 0xc0f5a8dea0)
	/go/src/github.com/appscode/kubed/vendor/golang.org/x/net/http2/server.go:2053 +0x89
Apr 11 02:13:44 kube-system kubed-kubed-86f55985f4-6jz2j:  github.com/appscode/kubed/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1(0x48bf840, 0xc02bfb4ee0, 0xc0b56ecb00)
	/go/src/github.com/appscode/kubed/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:41 +0x119
Apr 11 02:13:44 kube-system kubed-kubed-86f55985f4-6jz2j:  github.com/appscode/kubed/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc000578280, 0x48bf840, 0xc02bfb4ee0, 0xc0b56ecd00)
	/go/src/github.com/appscode/kubed/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:110 +0x2aa
Apr 11 02:13:44 kube-system kubed-kubed-86f55985f4-6jz2j:  github.com/appscode/kubed/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc050b66080, 0xc0e415fef0)
	/go/src/github.com/appscode/kubed/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:226 +0x1ae
Apr 11 02:13:44 kube-system kubed-kubed-86f55985f4-6jz2j:  github.com/appscode/kubed/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1.1(0x23179e0, 0xc000453320)
	/go/src/github.com/appscode/kubed/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:34 +0x74
Apr 11 02:13:44 kube-system kubed-kubed-86f55985f4-6jz2j:  github.com/appscode/kubed/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc00080f260, 0x48b4f40, 0xc018862310, 0xc0b56ecb00)
	/go/src/github.com/appscode/kubed/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
Apr 11 02:13:44 kube-system kubed-kubed-86f55985f4-6jz2j:  github.com/appscode/kubed/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x48bf840, 0xc02bfb4ee0, 0xc0b56ecb00)
	/go/src/github.com/appscode/kubed/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x217
Apr 11 02:13:44 kube-system kubed-kubed-86f55985f4-6jz2j:  github.com/appscode/kubed/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x48bf840, 0xc02bfb4ee0, 0xc0b56ecc00)
	/go/src/github.com/appscode/kubed/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:47 +0xd6
Apr 11 02:13:44 kube-system kubed-kubed-86f55985f4-6jz2j:  created by github.com/appscode/kubed/vendor/golang.org/x/net/http2.(*serverConn).processHeaders
	/go/src/github.com/appscode/kubed/vendor/golang.org/x/net/http2/server.go:1787 +0x459
Apr 11 02:13:44 kube-system kubed-kubed-86f55985f4-6jz2j:  github.com/appscode/kubed/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc060fb7ce8, 0x1, 0x1)
	/go/src/github.com/appscode/kubed/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:54 +0xc7
Apr 11 02:16:48 kube-system kubed-kubed-86f55985f4-6jz2j:  github.com/appscode/kubed/vendor/golang.org/x/net/http2.(*serverConn).runHandler.func1(0xc018862310, 0xc060fb7faf, 0xc000bc6000)
	/go/src/github.com/appscode/kubed/vendor/golang.org/x/net/http2/server.go:2046 +0x17c
Apr 11 02:16:48 kube-system kubed-kubed-86f55985f4-6jz2j:  github.com/appscode/kubed/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc050b66080, 0xc0e415fef0)
	/go/src/github.com/appscode/kubed/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:226 +0x1ae
Apr 11 02:16:48 kube-system kubed-kubed-86f55985f4-6jz2j:  github.com/appscode/kubed/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc000578280, 0x48bf840, 0xc02bfb4ee0, 0xc0b56ecd00)
	/go/src/github.com/appscode/kubed/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:110 +0x2aa
Apr 11 02:16:48 kube-system kubed-kubed-86f55985f4-6jz2j:  github.com/appscode/kubed/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc060fb7ce8, 0x1, 0x1)
	/go/src/github.com/appscode/kubed/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
Apr 11 02:16:48 kube-system kubed-kubed-86f55985f4-6jz2j:  created by github.com/appscode/kubed/vendor/golang.org/x/net/http2.(*serverConn).processHeaders
	/go/src/github.com/appscode/kubed/vendor/golang.org/x/net/http2/server.go:1787 +0x459
Apr 11 02:16:48 kube-system kubed-kubed-86f55985f4-6jz2j:  github.com/appscode/kubed/vendor/k8s.io/apiserver/pkg/server/filters.WithPanicRecovery.func1(0x48bf840, 0xc02bfb4ee0, 0xc0b56ecb00)
	/go/src/github.com/appscode/kubed/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:41 +0x119
Apr 11 02:16:48 kube-system kubed-kubed-86f55985f4-6jz2j:  github.com/appscode/kubed/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc00080f260, 0x48b4f40, 0xc018862310, 0xc0b56ecb00)
	/go/src/github.com/appscode/kubed/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
Apr 11 02:16:48 kube-system kubed-kubed-86f55985f4-6jz2j:  github.com/appscode/kubed/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x48bf840, 0xc02bfb4ee0, 0xc0b56ecb00)
	/go/src/github.com/appscode/kubed/vendor/k8s.io/apiserver/pkg/endpoints/filters/requestinfo.go:39 +0x217
Apr 11 02:16:48 kube-system kubed-kubed-86f55985f4-6jz2j:  github.com/appscode/kubed/vendor/k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x48bf840, 0xc02bfb4ee0, 0xc0b56ecc00)
	/go/src/github.com/appscode/kubed/vendor/k8s.io/apiserver/pkg/server/filters/waitgroup.go:47 +0xd6
Apr 11 02:16:48 kube-system kubed-kubed-86f55985f4-6jz2j:  github.com/appscode/kubed/vendor/golang.org/x/net/http2.(*serverConn).runHandler(0xc000bc6000, 0xc018862310, 0xc0b56ecb00, 0xc0f5a8dea0)
	/go/src/github.com/appscode/kubed/vendor/golang.org/x/net/http2/server.go:2053 +0x89
```

**Comment by sebastiansirch** [comment]
Another example about how the log file looks like when kubed is not working anymore but still reports to be "ready":

```
I0412 06:00:20.371087       1 logs.go:19] cron: panic running job: runtime error: invalid memory address or nil pointer dereference 
goroutine 250278 [running]: 
github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).runWithRecovery.func1(0xc000246230) 
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:161 +0xbc 
panic(0x2355fe0, 0x61654c0) 
	/usr/local/go/src/runtime/panic.go:513 +0x1b9 
github.com/appscode/kubed/pkg/recyclebin.(*RecycleBin).Cleanup(0xc000ad2a80, 0xc2219b0f90, 0x42b1d2) 
	/go/src/github.com/appscode/kubed/pkg/recyclebin/recycle_bin.go:115 +0x9c 
github.com/appscode/kubed/pkg/operator.(*Operator).RunTrashCanCleaner.func1() 
	/go/src/github.com/appscode/kubed/pkg/operator/operator.go:489 +0x2e 
github.com/appscode/kubed/vendor/github.com/robfig/cron.FuncJob.Run(0xc0002b0c50) 
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:92 +0x25 
github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).runWithRecovery(0xc000246230, 0x48950c0, 0xc0002b0c50) 
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:165 +0x57 
created by github.com/appscode/kubed/vendor/github.com/robfig/cron.(*Cron).run 
	/go/src/github.com/appscode/kubed/vendor/github.com/robfig/cron/cron.go:199 +0x6f4 
E0412 06:00:20.570906       1 writers.go:168] apiserver was unable to write a JSON response: http: Handler timeout 
E0412 06:00:21.768535       1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"} 
E0412 06:00:23.071706       1 writers.go:168] apiserver was unable to write a JSON response: http: Handler timeout 
E0412 06:00:23.271653       1 writers.go:168] apiserver was unable to write a JSON response: http: Handler timeout 
E0412 06:00:23.271698       1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"} 
E0412 06:00:23.974690       1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"} 
E0412 06:00:24.969819       1 writers.go:168] apiserver was unable to write a JSON response: http: Handler timeout 
E0412 06:00:25.268595       1 writers.go:168] apiserver was unable to write a JSON response: http: Handler timeout 
E0412 06:00:25.370407       1 writers.go:168] apiserver was unable to write a JSON response: http: Handler timeout 
E0412 06:00:25.569918       1 writers.go:168] apiserver was unable to write a JSON response: http: Handler timeout 
E0412 06:00:25.869778       1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"} 
E0412 06:00:27.468304       1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"} 
E0412 06:00:27.868205       1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"} 
E0412 06:00:27.968937       1 status.go:64] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"} 

```

**Comment by tamalsaha** [comment]
This should be fixed in https://github.com/appscode/kubed/releases/tag/v0.12.0-rc.0
