### ISSUE TITLE
Crash when the namespace is terminating

### ISSUE THREAD

**Issue by mbelang** [appscode/kubed#380]
With 0.12.rc1 I get this error and kube falls under crashloop backoff. This should be gracefully handled.

```E0113 13:51:19.508808       1 runtime.go:78] Observed a panic: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"configmaps \"global-environment\" is forbidden: unable to create new content in namespace xxxxxxxxxxxxxxxxxxxxxx because it is being terminated", Reason:"Forbidden", Details:(*v1.StatusDetails)(0xc0004462a0), Code:403}} (configmaps "global-environment" is forbidden: unable to create new content in namespace xxxxxxxxxxxxxxxxxxx because it is being terminated)
goroutine 183 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x19fc120, 0xc00109a280)
	/src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x19fc120, 0xc00109a280)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/apimachinery/pkg/util/runtime.Must(...)
	/src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:171
github.com/appscode/kubed/pkg/syncer.(*nsSyncer).OnAdd(0xc00013cb28, 0x1c0d1e0, 0xc0009466b8)
	/src/pkg/syncer/resourcehandlers.go:152 +0x122
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x2, 0x0, 0xc000469ea0)
	/src/vendor/k8s.io/client-go/tools/cache/shared_informer.go:658 +0x218
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc000955dd8, 0xc000469e20, 0x41efb0)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x51
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/src/vendor/k8s.io/client-go/tools/cache/shared_informer.go:652 +0x79
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000469f40)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000955f40, 0xdf8475800, 0x0, 0x42ec01, 0xc0004925a0)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0006f3900)
	/src/vendor/k8s.io/client-go/tools/cache/shared_informer.go:650 +0x9b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc000348990, 0xc0001da770)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x59
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
panic: configmaps "global-environment" is forbidden: unable to create new content in namespace xxxxxxxxxxxxxxxxxxxx because it is being terminated [recovered]
	panic: configmaps "global-environment" is forbidden: unable to create new content in namespacexxxxxxxxxxxxxxxxxxxxx because it is being terminated
```

**Comment by mbelang** [comment]
This problem is related to the fact that kubed is adding a finalizer to the namespace.

```apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2019-08-28T23:05:18Z"
  deletionTimestamp: "2020-01-13T13:51:26Z"
  labels:
    name: xxxxxxxxxxxxxx
  name: xxxxxxxxxxxxxx
  resourceVersion: "63474459"
  selfLink: /api/v1/namespaces/beautiful-mind-pr-284
  uid: 4df881c6-c9e8-11e9-824f-128071008574
spec:
  finalizers:
  - kubernetes
status:
  phase: Terminating
```

This is a show stopper for us as we need to be able to delete namespaces on the fly as we handle ephemeral deployments of services for testing purposes.

**Comment by mbelang** [comment]
I found the reason, the old CRD from 0.11.0 chart was still present and it was causing problems with finalizer. I updated to latest chart and everything is fixed now.
