### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tamalsaha** [appscode/kubed#59]
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x16910da]

goroutine 79 [running]:
github.com/appscode/kubed/vendor/github.com/appscode/go/runtime.HandleCrash(0x0, 0x0, 0x0)
    /go/src/github.com/appscode/kubed/vendor/github.com/appscode/go/runtime/runtime.go:58 +0x126
panic(0x18890c0, 0x26b2a60)
    /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/appscode/kubed/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
    /go/src/github.com/appscode/kubed/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
panic(0x18890c0, 0x26b2a60)
    /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/appscode/kubed/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
    /go/src/github.com/appscode/kubed/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
panic(0x18890c0, 0x26b2a60)
    /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/appscode/kubed/pkg/operator.(*Operator).watchService.func3(0x1a8ad00, 0xc421091000)
    /go/src/github.com/appscode/kubed/pkg/operator/service.go:49 +0x19a
github.com/appscode/kubed/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(0xc42074e730, 0xc42074e750, 0xc42074e740, 0x1a8ad00, 0xc421091000)
    /go/src/github.com/appscode/kubed/vendor/k8s.io/client-go/tools/cache/controller.go:192 +0x49
github.com/appscode/kubed/vendor/k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnAdd(0xc420411860, 0x1a8ad00, 0xc421091000)
    <autogenerated>:54 +0x73
github.com/appscode/kubed/vendor/k8s.io/client-go/tools/cache.NewInformer.func1(0x18aab80, 0xc42048aba0, 0x18aab80, 0xc42048aba0)
    /go/src/github.com/appscode/kubed/vendor/k8s.io/client-go/tools/cache/controller.go:270 +0x24d
github.com/appscode/kubed/vendor/k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc42007dc80, 0xc4200f4ba0, 0x0, 0x0, 0x0, 0x0)
    /go/src/github.com/appscode/kubed/vendor/k8s.io/client-go/tools/cache/delta_fifo.go:451 +0x27e
github.com/appscode/kubed/vendor/k8s.io/client-go/tools/cache.(*controller).processLoop(0xc420ddf280)
    /go/src/github.com/appscode/kubed/vendor/k8s.io/client-go/tools/cache/controller.go:147 +0x40
github.com/appscode/kubed/vendor/k8s.io/client-go/tools/cache.(*controller).(github.com/appscode/kubed/vendor/k8s.io/client-go/tools/cache.processLoop)-fm()
    /go/src/github.com/appscode/kubed/vendor/k8s.io/client-go/tools/cache/controller.go:121 +0x2a
github.com/appscode/kubed/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4208efe98)
    /go/src/github.com/appscode/kubed/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:96 +0x5e
github.com/appscode/kubed/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc420931e98, 0x3b9aca00, 0x0, 0x17b8601, 0xc420053740)
    /go/src/github.com/appscode/kubed/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97 +0xad
github.com/appscode/kubed/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4208efe98, 0x3b9aca00, 0xc420053740)
    /go/src/github.com/appscode/kubed/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52 +0x4d
github.com/appscode/kubed/vendor/k8s.io/client-go/tools/cache.(*controller).Run(0xc420ddf280, 0xc420053740)
    /go/src/github.com/appscode/kubed/vendor/k8s.io/client-go/tools/cache/controller.go:121 +0x237
github.com/appscode/kubed/pkg/operator.(*Operator).watchService(0xc4202d0c60)
    /go/src/github.com/appscode/kubed/pkg/operator/service.go:114 +0x58c
created by github.com/appscode/kubed/pkg/operator.(*Operator).RunWatchers
    /go/src/github.com/appscode/kubed/pkg/operator/operator.go:180 +0x461

```

**Comment by tamalsaha** [comment]
```
github.com/appscode/kubed/pkg/operator.(*Operator).watchService.func3(0x1a8ad00, 0xc421091000)
    /go/src/github.com/appscode/kubed/pkg/operator/service.go:49 +0x19a
```
